# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vq4iLzVXA_6qmeNt-rx2Q9lUgqsuj5aJ
"""

import numpy as np
import pandas as pd

#1
list1=np.array([1,2,3,4,5,6,7,8,9])
list_sum=np.sum(list1)
list_mean=np.mean(list1)
list_min=np.min(list1)
list_max=np.max(list1)
list_std=np.std(list1)
print(f"Sum:{list_sum} Mean:{list_mean} Minimum:{list_min} Maximum:{list_max} S.Deviation:{list_std}")

#2
health_data = np.array([[160, 70, 30],   # height, weight, age for individual 1
                        [165, 65, 35],   # height, weight, age for individual 2
                        [170, 75, 40]])  # height, weight, age for individual 3

#3
marks_data=np.array([[65,"exempt",78,86,66],['exempt',45,78,88,65]])
# arr=marks_data[:,2:][0]
# arr1=marks_data[:,2:][1]
# arr3=arr.astype(int)
# arr3=np.mean(arr)
c=0
for i in marks_data:
  val=i[2:]
  c=c+val[i]
a=np.mean(c)
a

#4
arr=np.linspace(15,25,14)
print(arr)

#5
import numpy as np
daily_closing_prices = np.array([100, 102, 98, 105, 107, 110, 108, 112, 115, 118, 120])
window_size = 5
arr=np.mean(daily_closing_prices)
arr

#6
np.ones(100)

#7
import numpy as np
properties_matrix = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
arr=np.deter(properties_matrix)

#8
mat1=[[1,2,3],[4,5,6],[7,8,9]]

#9
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}
df=pd.DataFrame(data)
df1=df[(df['Age']<45) & (df["Department"]!='HR')][["Name","City"]]
df1

#10
data = {'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]}
df=pd.DataFrame(data)
df.sort_index(data[Department])
# data1=data['Sales']
# data2=np.mean(data1)
# data3=df.sort_index('Department')
# data3

#11
data = {
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': [True, False, True, True, False, True, False]
}
df=pd.DataFrame(data)
df1=df[(df['Price']>(df['Price'].mean())) & (df["Promotion"]==False) &(df["Category"]=="Fruit")]

df1

#12
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
}

# Dataset of employee project assignments
project_data = {
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
}
employee_data.merge(project_data)

#13
df=pd.read_csv("/content/Q13_sports_team_stats.csv")
df

win_ratio=df1[(df1['Wins']/(df1['GamesPlayed']))]
win_ratio

#14
df=pd.read_csv("/content/Q14_customer_purchases.csv")

df1=df[(df['Date']<(df['LoyaltyProgramSignUp']))]
df1

#15
df=pd.read_csv("/content/Q15_student_grades.csv")
# df
df1=df[(df['Grade']<85)]
df1