# -*- coding: utf-8 -*-
"""LVADSUSR158_Jeno_Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRxrQjBp3dMLBeM3nYraUwUh5kY9S-MH
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.metrics import mean_squared_error,r2_score

df=pd.read_csv("/content/expenses.csv")
df

df.info()

df.shape

df.head()

df.describe()

df.dtypes

df.isna().sum()

plt.figure(figsize=(12,6))
sns.histplot(df['bmi'])
plt.title("Histogram of BMI")
plt.xlabel("BMI")
plt.ylabel("Count")

df['bmi']=df['bmi'].fillna(df['bmi'].mean())

df.isna().sum()

col=['sex','smoker','region']
for c in col:
  l=LabelEncoder()
  df[c]=l.fit_transform(df[c])
df

sns.boxplot(df[['age','bmi','children','charges']])
plt.title("Boxplot for outlier detection")

q1=df.quantile(0.25)
q3=df.quantile(0.75)
iqr=q3-q1

outliers=((df< q1-1.5*iqr) | (df> q3+1.5*iqr)).any(axis=1)
cleaned_df=df[~outliers]
cleaned_df

df.corr()

plt.figure(figsize=(20,12))
sns.heatmap(df.corr(),annot=True)

X=df.drop(columns=['charges','smoker'])
y=df['charges']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=42)

X_train

scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

y_pred[:5]

print("MSE: ",mean_squared_error(y_pred,y_test))
print("RMSE:",mean_squared_error(y_pred,y_test,squared=False))
print("R2 Score: ",r2_score(y_pred,y_test))



