# -*- coding: utf-8 -*-
"""IA-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eHPB3jvo1YlnQO1EMsnujrxrlZ3IxOc6
"""

#1
def property_size():
  length=float(input("Enter length of property(in m): "))
  width=float(input("Enter width of property(in m): "))
  area=length*width
  print("Total area is :"+str(area)+" m")
  if length>2500 or width>2500:
    print("Large Property")
  elif length<500 or width<500:
    print("Small property")
  else:
    print("Medium property")

property_size()

#2
height=float(input("Enter height (in m): "))
weight=float(input("Enter weight (in kgs): "))
bmi=weight/(height**2)
print(bmi)

s1={"name":"John","Maths":67,"SCience":78,"Social":87}
s2={"name":"Mary","Maths":89,"SCience":67,"Social":77}
print(s1,s2)
s1.update("name":"Abel")
s1.insert("Tamil":88)
print(s1)

#4
age=int(input("Enter your age: "))
if age < 14:
  print("Here are movie with ratings for children!")
elif age>14 and age<18:
  print("Here are movie with ratings for Teens!")
elif age>18 and age<30:
  print("Here are movie with ratings for Adults!")
else:
  print("Here are movie with ratings for Senior citizens!")

#5
list1=[101,102,103,104,105,106,107,108,109,110]
list2=[]
for i in range(0,len(list1)):
  if list1[i]%2==0:
    list2.append(list1[i])
print("The promotional email should be sent to these subscriberIds "+str(list2))

#6
stored_password="login123"
while True:
  password=input("enter password: ")
  if password==stored_password:
    print("Login successful!")
    break
  else:
    print("Wrong password")

#7
def satisfaction():
  c1=int(input("Enter rating of product (1 to 5): "))
  c2=int(input("Enter satisfaction based on quality (1 to 5): "))
  c3=int(input("Enter customer satisfaction rating (1 to 5): "))
  ct=c1+c2+c3
  ca=((c1+c2+c3)/3)
  if ct<5:
    print("Customer not satisfied")
  elif ct>=5 and ct<10:
    print("Customer partially satisfied")
  else:
    print("Customer Satisfied")
    print(f"Average customer feedback score is {ca}")

satisfaction()

#8
s1="abcde"
c=0
for i in range(0,len(s1)):
  if s1[i]=="a" or s1[i]=="e" or s1[i]=="i" or s1[i]=="o" or s1[i]=="u" :
    c+=1
if c<5:
  print("spam")
else:
  print("Not spam")
print(f"Number of vowels is {c}")

#9
import datetime
cur=datetime
n=input("Enter date:")
if n=="22-03-24":
  print("You have a meeting today")
else:
  print("You are free today")

#10
l=float(input("Enter loan amount: "))
i=float(input("Enter interest amount: "))
try:
  loan_repay=l+(l*i)
  print("Amount to repay: ",loan_repay)
except ZeroDivisionError:
  print("Wrong value")

#11
vote=input("Place your vote (X or Y): ")
x=0
y=0
for i in range(0,10):
  if (vote.lower()=="X"):
    x+=1
  elif (vote.lower()=="Y"):
    y+=1

print(x,y)

#12
a=int(input("Enter value1: "))
b=int(input("Enter value2: "))
add=a+b
sub=a-b
mul=a*b
try:
  div=a/b
except ZeroDivisionError:
  print("Except Clause")
print(add)
print(sub)
print(mul)
print(div)

#13
t1=open("sample.txt","w")
uptime=67
t1.write(str(uptime))

#14
t2=open("sample.txt","r")
logs=2546
t2.read(logs)

#15
t3=open("sample.txt","w")
stock="high"
value=10000
performance=10
t3.read(stock)
t3.read(value)
t3.read(performance)