# -*- coding: utf-8 -*-
"""LVADSUSR158_JenoClassificationFA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nS74ZCfNBgm2J09PJB5OhYq4_PqmMB9A
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler,OneHotEncoder, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,precision_score ,classification_report, f1_score, r2_score, mean_squared_error, accuracy_score, recall_score
warnings.filterwarnings('ignore')

df=pd.read_csv("/content/penguins_classification.csv")
df

df.info()

df.shape

df.describe()

df.dtypes

df.isna().sum()

df.duplicated().sum()

sns.histplot(df['bill_depth_mm'])

df['bill_depth_mm']=df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())

df.isna().sum()

plt.figure(figsize=(20,12))
sns.boxplot(df)

for column in df.select_dtypes(include=['object']).columns:
  l=LabelEncoder()
  df[column]=l.fit_transform(df[column])

df.corr()

plt.figure(figsize=(20,12))
sns.heatmap(df.corr(),annot=True)

X=df.drop(columns=['species'])
y=df['species']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
model=RandomForestClassifier(n_estimators=80)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

model.score(X_test,y_test)

print("Accuracy Score: ",accuracy_score(y_pred,y_test))
print("Recall Score: ",recall_score(y_pred,y_test))
print("Precision Score: ",precision_score(y_pred,y_test))
print("F1 Score: ",f1_score(y_pred,y_test))
print("Confusion Matrix: ",confusion_matrix(y_pred,y_test))
print("Classification Report: ",classification_report(y_pred,y_test))

"""Analysis:
The dataset had some null values in a column and it was filled by the mean values of the column. There were no significant outliers and hence it was not treated. Since the dataset is very small we were bale to achieve 100% accuracy using the Random Forest Classification Algorithm.
"""