# -*- coding: utf-8 -*-
"""LVADSUSR158_Jeno_RegressionFA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byJf4O1csBKyYXW14IrTlPAW2ktVGTkr
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler,OneHotEncoder, LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error
warnings.filterwarnings('ignore')

df=pd.read_csv("/content/Fare prediction.csv")
df

df.info()

df.shape

df.describe()

df.dtypes

df.isna().sum()

df.duplicated().sum()

for column in df.select_dtypes(include=['object']).columns:
  l=LabelEncoder()
  df[column]=l.fit_transform(df[column])

df.dtypes

plt.figure(figsize=(20,12))
sns.boxplot(df)

df.corr()

plt.figure(figsize=(20,12))
sns.heatmap(df.corr(),annot=True)

X=df.drop(columns=df[['fare_amount','pickup_longitude','dropoff_longitude']])
y=df['fare_amount']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

len(X_test)

scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
model= LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

y_pred[:5]

print("MSE:",mean_squared_error(y_pred,y_test))
print("RMSE:",mean_squared_error(y_pred,y_test,squared=False))
print("R2Score:",r2_score(y_pred,y_test))

"""Analysis:
The linear regression model for the fare prediction dataset was trained and executed. The object variables were label encoded and since there were no significant outliers, the outliers were not treated. There were not significant correlation between data aswell so no columns were droppped while developing the training set.
"""